'use client'
import "./globals.css";
import { CookiesProvider } from 'react-cookie';


// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <CookiesProvider>
          {children}
        </CookiesProvider>

      </body>
    </html>
  );
}
